/**
 * Minimal built-in style used by the renderer when no saved style is chosen.
 *
 * It targets the selector contract's class names (.resume, .resume-header,
 * .section, .entry, .skills-list) and falls back to plain element selectors
 * scoped inside .resume so any other contract class still renders readably.
 * Every custom property has a fallback value, so the style also works before
 * the global print stylesheet defines its variables.
 */

/** Display name of the built-in style, shown in the style dropdown. */
export const DEFAULT_STYLE_NAME = 'Minimal (built-in)'

/** Value used by the style dropdown to mean "use the built-in style". */
export const DEFAULT_STYLE_ID = 'builtin-minimal'

/** The minimal built-in CSS, applied after the base print stylesheet. */
export const DEFAULT_STYLE_CSS = [
  'body {',
  '  margin: 0;',
  '  color: var(--resume-text-color, #1a1a1a);',
  '  background: var(--resume-background-color, #ffffff);',
  '  font-family: var(--resume-font-family, Georgia, "Times New Roman", serif);',
  '  font-size: var(--resume-font-size, 11pt);',
  '  line-height: var(--resume-line-height, 1.45);',
  '}',
  '',
  '.resume {',
  '  box-sizing: border-box;',
  '  max-width: 100%;',
  '  margin: 0 auto;',
  '  padding: var(--resume-margin-top, 16mm) var(--resume-margin-right, 16mm)',
  '    var(--resume-margin-bottom, 16mm) var(--resume-margin-left, 16mm);',
  '}',
  '',
  '@media print {',
  '  .resume {',
  '    padding: 0;',
  '  }',
  '}',
  '',
  '.resume h1,',
  '.resume h2,',
  '.resume h3 {',
  '  margin: 0;',
  '  line-height: 1.2;',
  '}',
  '',
  '.resume p {',
  '  margin: 0 0 0.4em;',
  '}',
  '',
  '.resume ul,',
  '.resume ol {',
  '  margin: 0.25em 0 0.5em;',
  '  padding-left: 1.2em;',
  '}',
  '',
  '.resume li {',
  '  margin: 0 0 0.2em;',
  '}',
  '',
  '.resume a {',
  '  color: inherit;',
  '  text-decoration: none;',
  '}',
  '',
  '.resume-header {',
  '  margin-bottom: 1.25em;',
  '  padding-bottom: 0.6em;',
  '  border-bottom: 1px solid var(--resume-rule-color, #bbbbbb);',
  '}',
  '',
  '.resume-header h1 {',
  '  font-size: var(--resume-font-size-name, 20pt);',
  '  letter-spacing: 0.02em;',
  '}',
  '',
  '.section {',
  '  margin-bottom: 1.1em;',
  '}',
  '',
  '.section > h2 {',
  '  margin-bottom: 0.5em;',
  '  padding-bottom: 0.15em;',
  '  border-bottom: 1px solid var(--resume-rule-color, #bbbbbb);',
  '  font-size: var(--resume-font-size-section, 12pt);',
  '  color: var(--resume-accent-color, #1f3a5f);',
  '  letter-spacing: 0.08em;',
  '  text-transform: uppercase;',
  '}',
  '',
  '.entry {',
  '  margin-bottom: 0.8em;',
  '}',
  '',
  '.entry h3 {',
  '  font-size: 1em;',
  '}',
  '',
  '.skills-list {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 0.25em 0.9em;',
  '  margin: 0;',
  '  padding: 0;',
  '  list-style: none;',
  '}',
  '',
  '.skills-list li {',
  '  margin: 0;',
  '}',
].join('\n')